on:
  push:
    branches:
      - master

name: Build and deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: deploy # The branch the action should deploy to
          folder: dist # The folder the action should deploy